### ISSUE TITLE
Memcached taking days to inject public keys from text file

### ISSUE THREAD

**Issue by bodaciousbob** [franzkruhm/Plutus-Scroo#12]
Hello again Franzkruhm!

How long should I expect it to take when loading the DB of all public addresses with a balance?

Currently it takes about 2 hours to get to 8M addresses, no sanity checks are completed by then. Then it takes about 10 hours to get to 15M addresses. I killed the process last time and allocated more memory but the speed of address injection is unchanged.

Any way that I can get the filldb-text.py script to run - and finish - faster?

**Comment by franzkruhm** [comment]
No idea either tbh.

You are sure you are using a 64bit version of memcached? I'm asking because I had someone use the 32bit version and they kept getting errors because obviously the database won't fit in 32bit memory

**Comment by bodaciousbob** [comment]
Installed python 3.9.0

installed starkbank ecdsa

installed pymemcache

download list of BTC addresses from loyce, rename to data.txt and store in specified folder

open CMD, and start memcache by navigating to location and running "memcached -n 70 -m 5200 -M -t 12" (i have not done anything else with memcached like install, run it as a daemon, or set it as a service

run filldb-text.py - wait. I still haven't gotten it to complete, as it seems like it will take weeks.

Do I need to allocate resources to python? do I need to install or run memcached as a service?

Again, everything is running locally, nothing else is taking up CPU or RAM 
When not running memcache or injecting addresses: (1-10% cpu allocated, 17% ram allocated, 0% ssd allocated, HDDs 0% allocated, GPU 0% allocated)

when running memcache and injecting addresses: (15-17% cpu allocated, 18% ram allocated, 1% ssd allocated, HDDs 0% allocated, GPU 6% allocated)

Can you see any issues with it? I'm thinking theres something I'm doing wrong with memcache. But considering filldb-text.py is actually running and injecting addresses, it leads me to believe that memcache is working.

**Comment by franzkruhm** [comment]
You got this one right? don't use the one with balances

http://addresses.loyce.club/Bitcoin_addresses_October_28_2021.txt.gz

**Comment by bodaciousbob** [comment]
Correct, I'm using the one without balances.

**Comment by bodaciousbob** [comment]
Weird.

Uninstall python 3
Download py3.10, install to c:\ drive
download pymemcache, pip install
download starkbank, pip install
download memcache 1.4.5 amd64
download database, rename as data.txt in /database folder

cmd admin launch memcache by entering: memcached -n 70 -m 5200 -M -t 12
memcache service starts (can see it in task manager)

run filldb-text.py - and its about 3x slower now! 

for giggles i ran memcached as -vv and in the cmd window i could see it injecting addresses into the ram.

I have no idea why it's so slow. :S

**Comment by franzkruhm** [comment]
please note it the latest addresses from loyce.club seem to be a mess but I'm not sure that would impact performance.

**Comment by bodaciousbob** [comment]
Interestingly enough, I ran this on a different PC in a different location with similar results - would take days to inject the addresses into memcache.

Are you able to link to your versions of pymemcache and memcached that you're using? Do I need to do anything other to memcached other than run the memcached command you have on the front page of the scroo repository?

Wondering if you have had results from any other users that indicate a max 10 min memcached injection time.. 

Additionally, I tried running memcached as a service and also with win7 compatibility - no change. 

If you have time, Franz, can you verify the code for filldb-text.py is up to date and there is nothing superfluous in the code? I was downloading the code as a zip file, so maybe I'll try copy pasting the code into a new python idle file.

**Comment by bodaciousbob** [comment]
Also, I tried the Sept edition of the loyce club addresses - no change in injection time.

**Comment by franzkruhm** [comment]
This is what I have installed (from pip)

Package       Version
------------- --------
ecdsa         0.17.0
llvmlite      0.37.0
numba         0.54.0
numpy         1.20.3
opencv-python 4.5.3.56
pip           21.2.4
pymemcache    3.5.0
setuptools    58.0.4
six           1.16.0

and the memcached I am using is the one that could be found here
http://labs.northscale.com/memcached-packages/
but not anymore. to tell if it is the right one it comes with a pthreadGC2.dll unlike other builds I've seen.

**Comment by bodaciousbob** [comment]
Reinstalled 3.9 and the modules above, tried a may DB, same result.

Fudged the code, added a # to line 53 and all addresses injected in 1 min 59s. 

It'll hammer through about a million keys in a min. 

Thanks for your help, Franz!

**Comment by franzkruhm** [comment]
Line 53? the print statement?

**Comment by bodaciousbob** [comment]
That's correct. Seems it was bottle necking when python was trying to print the number of addresses injected into memcached. 

Once I prevented the print statement from executing, cpu usage skyrocketed to 100% and watched memcached take a couple gigs in task manager. Took 2 minutes

When it was printing, memcached would go up 10mb every 30 seconds or so.

**Comment by franzkruhm** [comment]
Thanks for the feedback.
I hesitated leaving the print but I decided to leave it since I didn't experience much of a performance hit
I should test it again

**Comment by bodaciousbob** [comment]
Wondering why there's a # on line 52 of filldb-text?

Also when scroo runs what do "evictions", "connections", and "reclaimed" refer to?

Also noticed there are a few other # throughout preventing other things from being printed. Just curious if there's anything else I should enable?

**Comment by franzkruhm** [comment]
the # commented stuff was there for testing, not needed anymore
and evictions, connections, reclaimed just keeps tracks of memcached stats. basically you don't want evictions because it means memcached is trying free memory and thus removing addresses

**Comment by bodaciousbob** [comment]
Thanks, Franz!

I hesitate to open another "issue" as this is more of a request.

Are you able to modify the code, such that your random keys are generated within a keyspace? The entire bitcoin keyspace lies between  0000000000000000000000000000000000000000000000000000000000000001  and fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140.

For example if I wanted to search only randomized keys that lie between 00000000000000000000000000000001f0000000000000000000000000000000 and   0000000000000000000000000000000af0000000000000000000000000000000

Are you able to modify the code such that the user can input the key space to search?

**Comment by franzkruhm** [comment]
I probably could do it, thing is I wasn't planning on maintaining this project much anymore. I wanted to move to something else.

along the lines of what you requested you have https://github.com/AlexCurl/BitCrack and derivatives that can do what you ask and use GPU. Thing is you will have to clean the list from loyce. as this tool is very picky about which addresses are valid or not.
