### ISSUE TITLE
Why only use half of available CPUs for tasks?

### ISSUE THREAD

**Issue by dojo90** [franzkruhm/Plutus-Scroo#13]
In line [30](https://github.com/franzkruhm/Plutus-Scroo/blob/master/scroo.py#L30) you divide the number of cpus to get the number of tasks. Does this have any particular reason?

**Comment by franzkruhm** [comment]
heat on the laptop I'm using
feel free to change it

**Comment by dojo90** [comment]
You will definitely get a better laptop from me should I find some coins 😄🍻
