### ISSUE TITLE
Modify code to specify private key range.

### ISSUE THREAD

**Issue by bodaciousbob** [franzkruhm/Plutus-Scroo#15]
Hi again, Franz!

Your code automatically generates a random private address of a specified length, and converts it into a public key to compare against a database of know addresses. 

How would one go about modifying the code, to vary the length of the random private key? Say if I wanted to generate a private key that consists of 4 characters, padded by 60 zeros, such that it's always 64 characters between 0 and f.

Seems like it shouldn't be too hard to do, my python is just very, very rusty. 

Thanks!

**Comment by franzkruhm** [comment]
it should be doable but I wasn't planning on maintaining this much longer
