### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by lk583998442** [franzkruhm/Plutus-Scroo#4]
execute python3 scroo.py

available threads: 4
Traceback (most recent call last):
  File "scroo.py", line 196, in <module>
    f = open('sanity.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'sanity.txt'

**Comment by franzkruhm** [comment]
you need to use filldb-text.py to load a list of addresses from a text file
filldb.py is no longer supported

**Comment by lk583998442** [comment]
> python filldb-text.py

  File "filldb-text.py", line 52
    print('\raddresses: ' + str(i_add), end=' ')
                                           ^
SyntaxError: invalid syntax

**Comment by franzkruhm** [comment]
this is odd, I just downloaded filldb-text.py from github to be sure and ran it, it works here.
what version of python are you using?

**Comment by lk583998442** [comment]
I used python 2.7.5

**Comment by franzkruhm** [comment]
This is for python 3.9.4 or +

**Comment by lk583998442** [comment]
I update python 3.9.5 ,but

[root@server franzkruhm-plutus-scroo]# python3 filldb-text.py connect memcached...
Loading and injecting database
06/06/2021, 18:26:40
Traceback (most recent call last):
  File "/root/franzkruhm-plutus-scroo/filldb-text.py", line 37, in <module>
    f = open(DATABASE_PATH, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'database/data.txt'

**Comment by franzkruhm** [comment]
download the latest database here
http://addresses.loyce.club/Bitcoin_addresses_LATEST.txt.gz
uncompress it
rename the file to data.txt and place it in database directory
