### ISSUE TITLE
Hello, Could you tell me how to run on windows 10?

### ISSUE THREAD

**Issue by vipvip1811** [franzkruhm/Plutus-Scroo#7]
On my windows PC this command not run: "memcached -n 70 -m 5200 -t 12"
and "python filldb-text.py" error
Thanks!

C:\Users\Yolo\Downloads\Plutus-Scroo-master\Plutus-Scroo-master>python filldb-text.py
connect memcached...
Loading and injecting database
06/08/2021, 23:33:21
Traceback (most recent call last):
  File "C:\Users\Yolo\Downloads\Plutus-Scroo-master\Plutus-Scroo-master\filldb-text.py", line 50, in <module>
    client.set_multi(dict.fromkeys(alist, 1), expire=0)
  File "C:\Users\Yolo\AppData\Local\Programs\Python\Python39\lib\site-packages\pymemcache\client\base.py", line 401, in set_many
    result = self._store_cmd(b'set', values, expire, noreply, flags=flags)
  File "C:\Users\Yolo\AppData\Local\Programs\Python\Python39\lib\site-packages\pymemcache\client\base.py", line 971, in _store_cmd
    self._connect()
  File "C:\Users\Yolo\AppData\Local\Programs\Python\Python39\lib\site-packages\pymemcache\client\base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by vipvip1811** [comment]
hello,
How to run memcached?
i run "memcached -n 70 -m 5200 -t 12" on CMD, but nothing happen

**Comment by franzkruhm** [comment]
have you downloaded memcached for windows ? https://github.com/nono303/memcached/tree/master/cygwin

**Comment by franzkruhm** [comment]
or this one? https://github.com/jefyt/memcached-windows

**Comment by vipvip1811** [comment]
thank you. It lauched.
But after run scroo.py, i see that program only check 2 address on sanity.txt, although i loaded 37mil data. i think the probability of finding 1 key will be much higher if run with all the data

**Comment by franzkruhm** [comment]
It checks ALL the addresses; the two random addresses selected are for "sanity testing the database" if they are still there the database should be okay, if they are not memcached had a problem.

**Comment by franzkruhm** [comment]
Just a note, after some testing with various versions, your results may vary but:

On windows 10 performance testing showed that memcached 1.4.5 performed better than recent versions (1.6...) taking 3.5mn to test 1 million addresses (instead of 5mn) on a i7-10750h laptop Thus an older version of memcached seems considerably faster. Thus at this time on Windows 10 the version of memcached I would recommend can be found at http://downloads.northscale.com/memcached-1.4.5-amd64.zip
