### ISSUE TITLE
No such file or directory: 'database/data.txt'

### ISSUE THREAD

**Issue by ashraful1980** [franzkruhm/Plutus-Scroo#9]
Dear Sir,
Please execute the data.txt file inside of database file..

![image](https://user-images.githubusercontent.com/52574658/128345120-72f462b8-de0f-484b-a7b3-aa8549b39fad.png)

**Comment by franzkruhm** [comment]
Yes you have to download the database from a source listed in the readme such as http://addresses.loyce.club/Bitcoin_addresses_LATEST.txt.gz and rename it the text file to data.txt
